import sys

# Map inputs from the terminal 
output_file = sys.argv[1]
input_files = sys.argv[2:]
# Open the final report file to write in the final outputs 
with open(output_file, 'w') as f_out:
    f_out.write("Pipeline Final Report\n")
    f_out.write("====================================================\n\n")
    # Iterate through every report file generated by the pipeline
    for file_path in input_files:
        f_out.write(f"Source File: {file_path}\n") # Lable the data 
        f_out.write("-" * 40 + "\n")
        try:
            with open(file_path, 'r') as f_in: # Open the individual report and read it
                f_out.write(f_in.read()) # Write it into a bigger file 
        except Exception as e:
            f_out.write(f"Error reading {file_path}: {e}\n") # Print error message to know if this went wrong 
        f_out.write("\n" + "="*40 + "\n\n") # Add space between sections 
